site_name: Grid
site_url: https://grid.sarantium.dev
site_description: Grid - A positioning framework for product development
repo_url: https://github.com/sarantium/grid
repo_name: sarantium/grid

theme:
  name: "material"
  icon:
    logo: material/view-grid-plus
  favicon: assets/view-grid-plus-outline-dark.png
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - search.highlight
    - search.share

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sarantium/grid
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ashvinparameswaran
    - icon: fontawesome/solid/globe
      link: https://sarantium.dev
  analytics:
    provider: google
    property: G-KKL5FCE0BT
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/sarantium/grid/issues/new/?title=[Feedback]+{title}+-+{url}" target="_blank" rel="noopener">telling us what you're missing</a>.

copyright: Copyright &copy; 2022 - 2023 Ashvin Parameswaran
edit_uri: ""

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Grid: README.md
  - Framework: table.md
  - Syntax: syntax.md
  - Usage: usage.md
  - Release Notes: release-notes.md
  - Reading List: reading-list.md
  - License: license.md
