site_name: Grid
site_url: https://grid.sarantium.dev
site_description: Grid - A positioning framework for product development
repo_url: https://github.com/sarantium/grid
repo_name: sarantium/grid

theme:
  name: "material"
  icon:
    logo: material/view-grid-plus
  favicon: assets/view-grid-plus-outline-dark.png
  palette:
    - scheme: default
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.tracking
    - search.highlight
    - search.share

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sarantium/grid
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ashvinparameswaran
    - icon: fontawesome/solid/globe
      link: https://sarantium.dev
  analytics:
    provider: google
    property: G-KKL5FCE0BT

copyright: Copyright &copy; 2022 - 2023 Sarantium
edit_uri: ""

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

plugins:
  - search

nav:
  - Grid: README.md
  - Framework: table.md
  - Getting Started:
      - Coordinates: coordinates.md
      - Discovery: discovery.md
  - Releases: releases.md
  - Citations: citations.md
